---
- name: Deploying container
  hosts: webservers
  become: yes
  tasks:
    - name: Instaling python pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Installing Docker SDK
      pip:
        name: docker
        state: present

    - name: Installing Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Making dokcer service running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pulling docker image
      docker_image:
        name: amaan00101/myjava-app
        tag: 9
        source: pull

    - name: Running docker container
      docker_container:
        name: my_test_container
        image: amaan00101/myjava-app:9
        state: started
        restart_policy: always
        ports:
          - "8091:80"

